#!/bin/bash

# Assignment #12 execution timing script.
#
# -----------------------------------------------------
# Initial checks.
#	Ensure executable files exists.
#	Ensure test file exists
#
if [ -z $1 ]; then
	echo "Usage:  ./a12timer <ast12_Executable>"
	exit
fi
#
if [ ! -e $1 ] || [ ! -x $1 ]; then
	echo "Error, unable to find assignment #12 $1 executable file."
	exit
fi
#
# -----------------------------------------------------
# Display cute header
#
bolded=`tput bold`
normal=`tput sgr0`
#
clear
echo "**********************************************"
echo -e "${bolded}Assignment #12 -> Timed Executions${normal}"
echo -e "This WILL take a few minutes...\n\n"
#
# -----------------------------------------------------
#  Times tests
#
echo "##############################################" > a12times.txt
echo -e "Starting Timed Executions\\n"
#
for cnt in {1..4..1}
do
	echo "Timed Test ($cnt thread) starting."
	echo -e "\\n-------------------" >> a12times.txt
	echo "Timed Test ($cnt thread)" >> a12times.txt
	(time ./$1 -th $cnt -lm 111111111111111111) > null.txt 2>> a12times.txt
	echo "Timed Test ($cnt thread) completed."
	echo
done
#
echo  >> a12times.txt
echo  >> a12times.txt
#
rm null.txt
#
# -----------------------------------------------------
# Done
#
echo
echo
echo "Timed Tests completed."
echo "See ${bolded}a12times.txt${normal} results."
echo

